# config
rss:            # link
favicon: https://i.loli.net/2017/11/26/5a19c0b50432e.png
blog_logo: https://i.loli.net/2017/11/26/5a19c0b50432e.png
header_image: https://i.loli.net/2017/11/26/5a19c56faa29f.jpg

# menu
menu:
  About: /about
  Archives: /archives
  # you can add here

# author
author_image:   # link

# Social Links
social:
  facebook: https://www.facebook.com
  twitter: https://www.twitter.com
  # You only can use that I have added, I will keep adding

# widget
widgets:
  recent_posts: true
  category: true
  tagcloud: true
  # This is a simple theme, I think 3 is enough.

# post
post_toc: true

# gallery
# https://github.com/sachinchoolur/lightgallery.js
lightgallery: true